### PR TITLE
Added es build with docker support for seamless deployment and development

### PR DESCRIPTION
**Pull request by Vswaroop04**

### CODE REVIEW

**Comment by Vswaroop04** [comment]
This Fixes the #42

**Comment by Vswaroop04** [comment]
@jindalujjwal0720  Hey can you check i have added Esbuild which is bundler and minifier that is designed to be extremely fast and efficient. It is written in Go and aims to dramatically speed up the process of bundling and minifying JavaScript and other assets like CSS and images for production and also added docker to enlight the development and deployment

**Comment by jindalujjwal0720** [comment]
> @jindalujjwal0720  Hey can you check i have added Esbuild which is bundler and minifier that is designed to be extremely fast and efficient. It is written in Go and aims to dramatically speed up the process of bundling and minifying JavaScript and other assets like CSS and images for production and also added docker to enlight the development and deployment
> 

Yes @Vswaroop04 , I saw your PR yesterday itself. Actually my team and I were a bit busy lately, so we soon will approve and merge it.

**Comment by Vswaroop04** [comment]
@jindalujjwal0720 Thank you

**Pull request merged**
