### PR TITLE
created test suites namely auth.test.js for Controller and Service

### PR DESCRIPTION
**Pull request by piyushkdas0611**
do check and review and if any change required do tell me

### CODE REVIEW

**Comment by jindalujjwal0720** [comment]
There are some changes like pass-by-reference problems in tests; currently, the app is not exported from index.js. Export that and run the tests to get an idea of changes.

**Comment by jindalujjwal0720** [comment]
@piyushkdas0611, It's great work of you but it will a problem in the long run if we will test routes.
It will be better if we test controllers instead of routes because in coming times, when we will incorporate middlewares and stuff, these will again fail and passing the tests this way will be of no use.
Can you please modify the controllers and service functions instead of routes?

**Comment by piyushkdas0611** [comment]
> @piyushkdas0611, It's great work of you but it will a problem in the long run if we will test routes.
> It will be better if we test controllers instead of routes because in coming times, when we will incorporate middlewares and stuff, these will again fail and passing the tests this way will be of no use.
> Can you please modify the controllers and service functions instead of routes?

By functions you mean the original functions? I didn't touch them much only added a email validator

**Comment by jindalujjwal0720** [comment]
> > @piyushkdas0611, It's great work of you but it will a problem in the long run if we will test routes.
> > It will be better if we test controllers instead of routes because in coming times, when we will incorporate middlewares and stuff, these will again fail and passing the tests this way will be of no use.
> > Can you please modify the controllers and service functions instead of routes?
> 
> By functions you mean the original functions? I didn't touch them much only added a email validator

No, I'm not saying that buddy.
The email validation is a good enhancement by you and is obviously required.

I was asking to test the controller functions instead of testing the API routes.

See the _tests/controllers/events.test.js_ for reference.

**Pull request closed without merging**
